{% set version = "0.9.12-4.7" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-bayesfactor
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/BayesFactor_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/BayesFactor/BayesFactor_{{ version }}.tar.gz
  sha256: f92720697f8dbda248c7977873d582dc802522851647d563c5bcb1cada4e377d

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-matrix >=1.1_1             # [build_platform != target_platform]
    - r-matrixmodels               # [build_platform != target_platform]
    - r-rcpp >=0.11.2              # [build_platform != target_platform]
    - r-rcppeigen >=0.3.2.2.0      # [build_platform != target_platform]
    - r-coda                       # [build_platform != target_platform]
    - r-gtools                     # [build_platform != target_platform]
    - r-hypergeo                   # [build_platform != target_platform]
    - r-mvtnorm                    # [build_platform != target_platform]
    - r-pbapply                    # [build_platform != target_platform]
    - r-stringr                    # [build_platform != target_platform]
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('m2w64_cxx') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-matrix >=1.1_1
    - r-matrixmodels
    - r-rcpp >=0.11.2
    - r-rcppeigen >=0.3.2.2.0
    - r-coda
    - r-gtools
    - r-hypergeo
    - r-mvtnorm
    - r-pbapply
    - r-stringr
  run:
    - r-base
    - r-matrix >=1.1_1
    - r-matrixmodels
    - r-rcpp >=0.11.2
    - r-rcppeigen >=0.3.2.2.0
    - r-coda
    - r-gtools
    - r-hypergeo
    - r-mvtnorm
    - r-pbapply
    - r-stringr

test:
  commands:
    - $R -e "library('BayesFactor')"           # [not win]
    - "\"%R%\" -e \"library('BayesFactor')\""  # [win]

about:
  home: https://richarddmorey.github.io/BayesFactor/
  license: GPL-2.0-only
  summary: A suite of functions for computing various Bayes factors for simple designs, including contingency tables, one- and two-sample designs, one-way designs, general ANOVA designs, and linear regression.
  license_family: GPL2
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
