travis:
  secure:
    BINSTAR_TOKEN: vrzQkiKDFMbkzm3UUViZlI/N2vBDg/E84riNaCohY9A00fwBE9362SPk76QBPskxuSDgHQ5Fw0XTO1nBp7SS/m/z7Te8jzdWHQ019TQNmadF3FEKUZziOwvaMF3i4OvH7teaLVg82mJovqxOxFasRVjPbKVRDMGgD56arow1eGhBdPF7VmWnqAK/bYgXTAmCXBL+XfxE+6sHTgPrbBGPfdge6u6ivUtlkxjKVFdWBre0p1788h+1OBKaI4Xc64fg1Mg33duNguq5wlhXL9kq2MfLQ8EVgDhgIGEv7QWGiHxYL5IU85EsV2awGpZgk9/tzwqSvBoOzdpSQTtiHLXH1FjL1SL68WwrFU2WYf6dGxcHglwg9NzzTIAyaoF2wcMg7Kst8jaNOjg/PySNZNJLHqDRPlIW8rnJV6AFS5dQj1p+7QaSk/PcmdNvEs4yXl4e5oc5cw7I8lYUlB0MnIQ3el7QQVZcGyu8lkjWRwfct1rAARgkKIDdaN8+5Wumi+RHYjjUyYrEYH8TduiGyShVq5BJV+y/7/o9amI801Hxvno63GID1EpcU5Y/DDT3xPv/kzQSpl8EcbXQwudmv1d/BxjEsdxT4CjEVlT4ia0WnV9mpIs+GuIC7qZAsmVjfgMo8KU9EDScne5Bqjlh3PQFiPa1BRGJjeeiuV2+ZdbzSsk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
