travis:
  secure:
    BINSTAR_TOKEN: NVYmbtyQXMHtSKLiulX51IIdBOmWjKpUCGnWWp+OXUh3QtC6LKFA5ISX+COdpRbWGskRfn7YBDG48daz1eLxF1zC2Br4i40A/ZWBoUk+u+h0eUWL6KPGA6V10XEtRv3NQp5hQT0c4AgBtPmUBWauQ/W00xT3FrY0UKJPaJLEKVkApCjQRRjTmKIViUVBc75CycTTwAF9946SmMjN9LlEi4hnC4PXfeb9n++0MphqJBsd/iH7xS0nRdXRkHh0JhXDKPDaLCRsZkQkza1XtvHx2Gqs2LtPdPbqMJffgpft9qqWkZKceU3ZEDffBhAgpKd0Gx5NHEMDEYCtoIhfQBetvziCzAsrkbkM2CrWct0Y64PnNhQwiuA6RgSs1ifkv1vnf7k+SlVYoYF22UWOKSeCRO/3NdG6k7+bdj2QYxdYHxgwdCgvwiMFbhJSrAgAqksigZuyxNSUmlyzJUddIs3WjqJrz6mPwaHXmUKS7AcxIH03O9+JNQ8q7GgpxFkY4tPoBc46cHo+a+VtKWTlI0aJNjAu3IezirfcbVHy1sIV+RlZxRqP0mj8MCx7oZBIgjwe8GLMosqg7HjUdmfufxTU6VE6tZ0g8Ae4sDR0mUegvdPF2uhsCtcFE+JmCzH+zTqqp5Rf9V2/rvEb6yf36CnZ7rJJ7bV3w5LbdSvs91gTGvg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
